version: "3.7"

services:
  server:
    image: tumypmyp/chess-bot
    build: 
      context: .
      dockerfile: bot_service/Dockerfile
    environment:
      - TELEGRAM_APITOKEN=0123:TelegramTOKEN

  leaderboard:
    image: tumypmyp/chess-leaderboard
    build:
      context: .
      dockerfile: leaderboard_service/Dockerfile

  player:
    image: tumypmyp/chess-player
    build:
      context: .
      dockerfile: player_service/Dockerfile
  
  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 
    volumes: 
      - cache:/data
      
volumes:
  cache:
    driver: local


