# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build bot
      run: go build -v ./bot_service

    - name: Test bot
      run: go test -v ./bot_service
      
      
    - name: Build leaderboard
      run: go build -v ./leaderboard_service

    - name: Test leaderboard
      run: go test -v ./leaderboard_service
