
name: Deploy Leaderboard

on:
  push:
    branches: [ "main" ]
    paths:
      - 'leaderboard/**'
      - 'leaderboard_service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'leaderboard/**'
      - 'leaderboard_service/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: Build leaderboard
      run: go build -o ./service -v ./leaderboard_service

    - name: Test leaderboard
      run: go test -v ./leaderboard_service
